/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import model.bean.CatProduto;
import model.dao.CatProdutoDao;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author JaYVi
 */
public class TelaCatProdutos extends javax.swing.JFrame {

    /**
     * Creates new form TelaCatProdutos
     */
    public TelaCatProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDescricao = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCatProdutos = new javax.swing.JTable();
        txtdescricao = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jcbStatus = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Tipos de Produto");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtDescricao.setEnabled(false);

        tblCatProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        tblCatProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCatProdutosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCatProdutos);

        txtdescricao.setText("Descrição:");

        btnNovo.setIcon(new javax.swing.ImageIcon("C:\\Users\\JaYVi\\Downloads\\Icones JV\\New-48.png")); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.setPreferredSize(new java.awt.Dimension(50, 50));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAdicionar.setIcon(new javax.swing.ImageIcon("C:\\Users\\JaYVi\\Downloads\\Icones JV\\Save-48.png")); // NOI18N
        btnAdicionar.setToolTipText("Salvar");
        btnAdicionar.setEnabled(false);
        btnAdicionar.setMaximumSize(new java.awt.Dimension(80, 57));
        btnAdicionar.setPreferredSize(new java.awt.Dimension(50, 50));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\JaYVi\\Downloads\\Icones JV\\Edit-48.png")); // NOI18N
        btnEditar.setToolTipText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.setPreferredSize(new java.awt.Dimension(50, 50));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon("C:\\Users\\JaYVi\\Downloads\\Icones JV\\Cancel-48.png")); // NOI18N
        btnCancelar.setToolTipText("Cancel");
        btnCancelar.setEnabled(false);
        btnCancelar.setMaximumSize(new java.awt.Dimension(80, 57));
        btnCancelar.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtId.setEnabled(false);

        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATIVO", "INATIVO" }));
        jcbStatus.setEnabled(false);
        jcbStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbStatusMouseClicked(evt);
            }
        });
        jcbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbStatusActionPerformed(evt);
            }
        });

        jLabel6.setText("Status:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtdescricao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtDescricao)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdescricao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(514, 260));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Método para limpar campos
    private void limparCampos() {
        txtDescricao.setText(null);
        jcbStatus.setSelectedIndex(0);

    }
    //Fim Método para limpar campos

    //Método para habilitar campos
    private void habilitarCampos() {
        txtDescricao.setEnabled(true);
        jcbStatus.setEnabled(true);
    }
    //Fim Método habilitar campos

    //Método desabilitar Campos
    private void desabilitarCampos() {
        txtDescricao.setEnabled(false);
        jcbStatus.setEnabled(false);
    }
    //Fim Método desabilitar Campos

    //Menu de botões - Padronizar
    public void botaoNovo() {
        btnNovo.setEnabled(true);
        btnAdicionar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnCancelar.setEnabled(true);
    }

    public void botaoAdicionar() {
        btnNovo.setEnabled(true);
        btnAdicionar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnCancelar.setEnabled(false);
    }

    public void botaoDeletar() {
        btnNovo.setEnabled(true);
        btnAdicionar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnCancelar.setEnabled(false);
    }

    public void botaoSetarCampos() {
        btnNovo.setEnabled(false);
        btnAdicionar.setEnabled(false);
        btnEditar.setEnabled(true);
        btnCancelar.setEnabled(true);
    }

    public void botaoCancelar() {
        btnNovo.setEnabled(true);
        btnAdicionar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnCancelar.setEnabled(false);
    }
    //Fim do Menu de botões - Padronizar

    //Método para Validar Campos   
    public boolean validarCampos() {
        if (txtDescricao.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Digite a descrição do produto!");
            txtDescricao.requestFocus();
            return false;
        }
        return true;
    }
    //Fim Método para Validar Campos  


    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        limparCampos();
        habilitarCampos();
        tblCatProdutos.setEnabled(false);
        botaoNovo();
        txtDescricao.requestFocus();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        if (validarCampos() == true) {
            CatProduto cp = new CatProduto();
            CatProdutoDao dao = new CatProdutoDao();
            // CatProduto categoria = (CatProduto) jcbCategoria.getSelectedItem();

            cp.setDescricao(txtDescricao.getText());
            cp.setTipo("Produto");
            if (jcbStatus.getSelectedItem() == "ATIVO") {
                cp.setStatus(1);
            } else if (jcbStatus.getSelectedItem() == "INATIVO") {
                cp.setStatus(2);
            }
            dao.create(cp);

            limparCampos();
            desabilitarCampos();
            tblCatProdutos.setEnabled(true);
            botaoAdicionar();
            atualizarDadosGrid();
        }
        //  btnPesquisar.doClick();
    }//GEN-LAST:event_btnAdicionarActionPerformed


    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limparCampos();
        desabilitarCampos();
        //btnPesquisar.setEnabled(true);
        tblCatProdutos.setEnabled(true);
        atualizarDadosGrid();
        botaoCancelar();
        txtdescricao.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        atualizarDadosGrid();
    }//GEN-LAST:event_formWindowOpened

    private void tblCatProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCatProdutosMouseClicked
        // TODO add your handling code here:
        setar_campos();
    }//GEN-LAST:event_tblCatProdutosMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if (validarCampos() == true) {
            CatProduto cp = new CatProduto();
            CatProdutoDao dao = new CatProdutoDao();
            cp.setId(Integer.parseInt(txtId.getText()));
            cp.setDescricao(txtDescricao.getText());
            if (jcbStatus.getSelectedItem() == "ATIVO") {
                cp.setStatus(1);
            } else if (jcbStatus.getSelectedItem() == "INATIVO") {
                cp.setStatus(2);
            }
            dao.alterar(cp);
            limparCampos();
            desabilitarCampos();

            tblCatProdutos.setEnabled(true);
            botaoAdicionar();
            atualizarDadosGrid();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void jcbStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbStatusMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jcbStatusMouseClicked

    private void jcbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbStatusActionPerformed
        // Adiciona o item faltando no combobox
        if (jcbStatus.getItemCount() < 2) {
            if (jcbStatus.getSelectedItem() == "ATIVO") {
                jcbStatus.addItem("INATIVO");
            } else if (jcbStatus.getSelectedItem() == "INATIVO") {
                jcbStatus.addItem("ATIVO");
            }
        }
    }//GEN-LAST:event_jcbStatusActionPerformed

    //Passar dados para a tabela
    public void atualizarDadosGrid() {
        CatProdutoDao cat = new CatProdutoDao();
        ResultSet rs = null;

        tblCatProdutos.setEnabled(true);
        tblCatProdutos.setModel(DbUtils.resultSetToTableModel(cat.consultarProduto()));
        tblCatProdutos.getColumn(tblCatProdutos.getColumnName(0)).setMinWidth(0);
        tblCatProdutos.getColumn(tblCatProdutos.getColumnName(0)).setMaxWidth(0);
        tblCatProdutos.getColumn(tblCatProdutos.getColumnName(1)).setPreferredWidth(150);
        tblCatProdutos.getColumn(tblCatProdutos.getColumnName(3)).setMinWidth(0);
        tblCatProdutos.getColumn(tblCatProdutos.getColumnName(3)).setMaxWidth(0);
    }
    //Fim Passar dados para a tabela

    public void setar_campos() {
        int setar = tblCatProdutos.getSelectedRow();
        txtId.setText(tblCatProdutos.getModel().getValueAt(setar, 0).toString());
        txtDescricao.setText(tblCatProdutos.getModel().getValueAt(setar, 1).toString());
        if (tblCatProdutos.getModel().getValueAt(setar, 2).equals(1)) {
            jcbStatus.removeAllItems();
            jcbStatus.addItem("ATIVO");
        } else if (tblCatProdutos.getModel().getValueAt(setar, 2).equals(2)) {
            jcbStatus.removeAllItems();
            jcbStatus.addItem("INATIVO");
        }
        habilitarCampos();
        botaoSetarCampos();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCatProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCatProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCatProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCatProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCatProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcbStatus;
    private javax.swing.JTable tblCatProdutos;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtId;
    private javax.swing.JLabel txtdescricao;
    // End of variables declaration//GEN-END:variables
}
