-- MySQL Script generated by MySQL Workbench
-- Fri Jun  5 16:58:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbsalao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbsalao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbsalao` DEFAULT CHARACTER SET utf8 ;
USE `dbsalao` ;

-- -----------------------------------------------------
-- Table `dbsalao`.`ficha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsalao`.`ficha` (
  `ficha_id` INT NOT NULL AUTO_INCREMENT,
  `ficha_valortotal` DOUBLE(9,2) NOT NULL,
  `ficha_ultpagamento` DATE NULL,
  `ficha_ultcompra` DATE NULL,
  `ficha_pontuacao` INT NOT NULL,
  `ficha_dtabertura` DATE NOT NULL,
  PRIMARY KEY (`ficha_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsalao`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsalao`.`cliente` (
  `cliente_id` INT NOT NULL AUTO_INCREMENT,
  `cliente_nome` VARCHAR(45) NOT NULL,
  `cliente_endereco` VARCHAR(45) NULL,
  `bairro_tbcli` VARCHAR(30) NULL,
  `cliente_cidade` VARCHAR(30) NULL,
  `cliente_uf` VARCHAR(2) NULL,
  `cliente_cep` VARCHAR(9) NULL,
  `cliente_telefone` VARCHAR(13) NULL,
  `cliente_ficha_id` INT NOT NULL,
  INDEX `cliente_ficha_id_idx` (`cliente_ficha_id` ASC) VISIBLE,
  PRIMARY KEY (`cliente_id`),
  CONSTRAINT `cliente_ficha_id`
    FOREIGN KEY (`cliente_ficha_id`)
    REFERENCES `dbsalao`.`ficha` (`ficha_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsalao`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsalao`.`usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_nome` VARCHAR(40) NOT NULL,
  `usuario_login` VARCHAR(20) NOT NULL,
  `usuario_senha` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsalao`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsalao`.`categoria` (
  `categoria_id` INT NOT NULL AUTO_INCREMENT,
  `categoria_descricao` VARCHAR(45) NOT NULL,
  `categoria_tipo` INT NOT NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsalao`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsalao`.`produto` (
  `produto_id` INT NOT NULL AUTO_INCREMENT,
  `produto_descricao` VARCHAR(45) NOT NULL,
  `produto_data` DATE NOT NULL,
  `produto_valor` DOUBLE(9,2) NOT NULL,
  `produto_categoria_id` INT NOT NULL,
  `produto_pontfid` INT NOT NULL,
  `produto_status` INT NOT NULL,
  PRIMARY KEY (`produto_id`),
  INDEX `produto_categoria_id_idx` (`produto_categoria_id` ASC) VISIBLE,
  CONSTRAINT `produto_categoria_id`
    FOREIGN KEY (`produto_categoria_id`)
    REFERENCES `dbsalao`.`categoria` (`categoria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsalao`.`formapagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsalao`.`formapagamento` (
  `formpag_id` INT NOT NULL AUTO_INCREMENT,
  `formpag_descricao` VARCHAR(45) NOT NULL,
  `formpag_tipo` INT NOT NULL,
  `formpag_qtde_parc` INT NOT NULL,
  PRIMARY KEY (`formpag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsalao`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsalao`.`venda` (
  `venda_id` INT NOT NULL AUTO_INCREMENT,
  `venda_id_formadepagamento` INT NOT NULL,
  `venda_id_cliente` INT NOT NULL,
  `venda_datavenda` DATE NOT NULL,
  `venda_valortotal` DOUBLE(9,2) NOT NULL,
  `venda_desconto` DOUBLE(9,2) NULL,
  PRIMARY KEY (`venda_id`),
  INDEX `venda_id_cliente_idx` (`venda_id_cliente` ASC) VISIBLE,
  INDEX `venda_id_formadepagamento_idx` (`venda_id_formadepagamento` ASC) VISIBLE,
  CONSTRAINT `venda_id_cliente`
    FOREIGN KEY (`venda_id_cliente`)
    REFERENCES `dbsalao`.`cliente` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `venda_id_formadepagamento`
    FOREIGN KEY (`venda_id_formadepagamento`)
    REFERENCES `dbsalao`.`formapagamento` (`formpag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsalao`.`itensvenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsalao`.`itensvenda` (
  `itensvenda_id_venda` INT NOT NULL,
  `itensvenda_id_produto` INT NOT NULL,
  `itensvenda_descricao` VARCHAR(45) NOT NULL,
  `itensvenda_quant` INT NOT NULL,
  `itensvenda_total` DOUBLE(9,2) NOT NULL,
  PRIMARY KEY (`itensvenda_id_venda`, `itensvenda_id_produto`),
  INDEX `itensvenda_id_produto_idx` (`itensvenda_id_produto` ASC) VISIBLE,
  CONSTRAINT `itensvenda_id_venda`
    FOREIGN KEY (`itensvenda_id_venda`)
    REFERENCES `dbsalao`.`venda` (`venda_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `itensvenda_id_produto`
    FOREIGN KEY (`itensvenda_id_produto`)
    REFERENCES `dbsalao`.`produto` (`produto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsalao`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsalao`.`estoque` (
  `estoque_id` INT NOT NULL AUTO_INCREMENT,
  `estoque_id_produto` INT NOT NULL,
  `estoque_quant` INT NOT NULL,
  `estoque_valor` DOUBLE NOT NULL,
  PRIMARY KEY (`estoque_id`, `estoque_id_produto`),
  INDEX `estoque_id_produto_idx` (`estoque_id_produto` ASC) VISIBLE,
  CONSTRAINT `estoque_id_produto`
    FOREIGN KEY (`estoque_id_produto`)
    REFERENCES `dbsalao`.`produto` (`produto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsalao`.`parcela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsalao`.`parcela` (
  `parcela_id` INT NOT NULL AUTO_INCREMENT,
  `parcela_cod_venda` INT NOT NULL,
  `parcela_data` DATE NOT NULL,
  `parcela_pago` DOUBLE(9,2) NULL,
  `parcela_aberto` DOUBLE(9,2) NULL,
  `parcela_cod_ficha` INT NOT NULL,
  PRIMARY KEY (`parcela_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsalao`.`pag_parc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsalao`.`pag_parc` (
  `pag_parc_id` INT NOT NULL,
  `pag_parc_item` INT NOT NULL,
  `pag_parc_data` DATE NOT NULL,
  `pag_parc_valor` DOUBLE(9,2) NOT NULL,
  `pag_parc_tipo` INT NULL,
  `pag_parc_cod_ficha` INT NOT NULL,
  PRIMARY KEY (`pag_parc_id`, `pag_parc_item`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
